{
  "formatVersion": "1.1",
  "component": {
    "group": "com.team4188",
    "module": "voyager",
    "version": "26.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "voyager-26.1.0.jar",
          "url": "voyager-26.1.0.jar",
          "size": 38095,
          "sha512": "647513e079a745438fa4b6571d7ffa3335f4b77c487487cf706c9665ee53f4dfc25b3dcbed97e0a9a8fd4cd65189b2dd0dd49d27838d18a44afd66760dc6526d",
          "sha256": "3da8df18832b8f5cde85871cee9fdfc09c1ff9166c5cff5512234fa0e9096430",
          "sha1": "50c32686fc7db4081988b2c0858e45cda15e40db",
          "md5": "ef00743b82338aa789a20ae63b1ccaa3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.apriltag",
          "module": "apriltag-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.epilogue",
          "module": "epilogue-runtime-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2025.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "4.10.0-3"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-simple",
          "version": {
            "requires": "0.44.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "us.hebi.quickbuf",
          "module": "quickbuf-runtime",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "edu.wpi.first.wpilibNewCommands",
          "module": "wpilibNewCommands-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "com.github.edanliahovetsky",
          "module": "BLine-Lib",
          "version": {
            "requires": "v0.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "voyager-26.1.0.jar",
          "url": "voyager-26.1.0.jar",
          "size": 38095,
          "sha512": "647513e079a745438fa4b6571d7ffa3335f4b77c487487cf706c9665ee53f4dfc25b3dcbed97e0a9a8fd4cd65189b2dd0dd49d27838d18a44afd66760dc6526d",
          "sha256": "3da8df18832b8f5cde85871cee9fdfc09c1ff9166c5cff5512234fa0e9096430",
          "sha1": "50c32686fc7db4081988b2c0858e45cda15e40db",
          "md5": "ef00743b82338aa789a20ae63b1ccaa3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "voyager-26.1.0-sources.jar",
          "url": "voyager-26.1.0-sources.jar",
          "size": 11742,
          "sha512": "116fb7f7cbea404e8bf94ce7da84386e980a9f83f6dfc28ce3997108e40964285c58e37f1842f0a67f2e309e16cc835377add1d976411da7efdbfc3cf4685354",
          "sha256": "b4e2c14d0dc4dc9498df841c45889b680ecf38773154312dad04a21bcb97b787",
          "sha1": "eadcbd61e7fe30bf3f6d48c18782ff14a4cfcf3a",
          "md5": "69b6c6a2c7008dfd5c8a8840f96a18ea"
        }
      ]
    }
  ]
}
